[tool.flet.android.permission] # --android-permissions
"android.permission.INTERNET" = true
"android.permission.ACCESS_NETWORK_STATE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true

[tool.flet.android]
min_sdk_version = 21


dependencies = [
    "flet==0.28.3",
    "python-dotenv>=1.0.0",
    "requests>=2.28.0",
    "asyncio>=3.4.3"
]